apiVersion: apps/v1
kind: Deployment
metadata:
  name: aditya-deployment
  labels:
    app: aditya
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aditya
  template:
    metadata:
      labels:
        app: aditya
    spec:
      containers:
      - name: aditya
        image: aditya702077490/kubernetesproject
        ports:
        - containerPort: 80
